name = "ping-me-dc-users-online"
main = "dist/app.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat"  ]


# Custpm build
[build]
command = "npm run build"


[triggers]
crons = ["*/1 * * * *"] # every one min

[observability.logs]
enabled = true